# Generated by Django 4.1.3 on 2022-12-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_nombre', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('u_apellido', models.CharField(max_length=30)),
                ('u_documento', models.CharField(max_length=30, unique=True)),
                ('u_telefono', models.PositiveIntegerField()),
                ('u_email', models.EmailField(max_length=35)),
                ('u_direccion', models.CharField(max_length=35)),
                ('u_tipo', models.CharField(choices=[('Asociado', 'Asociado'), ('Recepcionista', 'Recepcionista'), ('Almacenista', 'Almacenista')], default='Asociado', max_length=13)),
                ('u_observaciones', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bovino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_nombre', models.CharField(max_length=90, unique=True, verbose_name='Nombre')),
                ('b_regICA', models.CharField(max_length=30)),
                ('b_aftosa', models.CharField(choices=[('0', 'NO'), ('1', 'SI')], default='1', max_length=1)),
                ('b_brucelosis', models.CharField(choices=[('0', 'NO'), ('1', 'SI')], default='1', max_length=1)),
                ('estado', models.CharField(choices=[('2', 'Activo'), ('1', 'Inactivo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usuario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
        ),
    ]
