# Generated by Django 4.1.3 on 2022-12-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='u_apellido',
            field=models.CharField(max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='u_direccion',
            field=models.CharField(max_length=35, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='u_documento',
            field=models.CharField(max_length=30, unique=True, verbose_name='Documento'),
        ),
    ]
