# Generated by Django 4.1.3 on 2022-12-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_rename_u_apellido_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='u_nombre',
        ),
    ]
