# Generated by Django 4.1.3 on 2022-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_rename_nombre_usuario_u_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='u_nombre',
            new_name='nombre',
        ),
    ]
