# Generated by Django 4.1.3 on 2022-12-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_rename_u_nombre_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='u_observaciones',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nombre'),
        ),
    ]
