# Generated by Django 4.1.3 on 2022-12-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_hora', models.TimeField(auto_now=True)),
                ('e_fecha', models.DateField(auto_now=True)),
                ('e_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
            options={
                'verbose_name_plural': 'entregasExternas',
                'db_table': 'entregaExterna',
            },
        ),
        migrations.CreateModel(
            name='EntregaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_hora', models.TimeField(auto_now=True)),
                ('e_fecha', models.DateField(auto_now=True)),
                ('e_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario')),
            ],
            options={
                'verbose_name_plural': 'entregasClientes',
                'db_table': 'entregaCliente',
            },
        ),
    ]
