# Generated by Django 4.1.3 on 2022-12-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='E_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entregas.entregacliente'),
        ),
    ]
